import Head from 'next/head'
import { useState } from 'react'
import Router, { useRouter } from 'next/router';
import Link from 'next/link';

import styles from '../styles/AddHabit.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChevronLeft } from "@fortawesome/free-solid-svg-icons";
import addHabit from '../hooks/useAddHabit';
import useDOY from '../hooks/useDOY';
import { supabase } from '../utils/supabase';

export default function EditHabit(props) {
	const router = useRouter();
	const { DateTime } = require("luxon");
	const { query } = router
	const [state, setState] = useState({
    title: (query.title || ""),
    color: (query.color || "#000000"),
    description: (query.description || ""),
    frequency: (query.frequency || []),
		error: false
  })
	console.log(query)
	console.log(props)
	console.log(props.query)

	// Change state for all keys except status and frequency
	const changeState = (key: string, val: string | boolean) => {
		setState({...state, [key]: val })
	}

	// Returns whether frequency contains the specific value
	const selected = (val: string) => {
		return state.frequency.includes(val)
	}

	// change status and frequency on button click
	const changeStatusAndFrequency = (val: string) => {
		let newFrequency = [...state.frequency]
		// If day clicked is in frequency, remove it, otherwise add it
		// similarly update status
		if (selected(val)) {
			newFrequency = newFrequency.filter(day => day !== val)
		} else {
			newFrequency.push(val)
		}
		setState({...state, frequency: newFrequency, error: false })
	}

	const completionTemplate = () => {
		const week: string[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
		const template = week.map((day) => {
			if (state.frequency.includes(day)) {
				return 0
			} else {
				return -1
			}
		})
		return template;
	}


	// new habit for submission
	const newHabit = {
		title: state.title,
		color: state.color,
		description: state.description,
		frequency: state.frequency,
		template: completionTemplate(),
		completion: completionTemplate(),
		weekStart: DateTime.now().startOf('week'),
		creationDate: DateTime.now()
	}

	// add habit to database
	const handleSubmit = async (event: { preventDefault: () => void; }) => {
		event.preventDefault()
		// If frequency is not empty, add habit to database
		if (state.frequency.length > 0) {

			const { data, error } = await supabase
			.from('habits')
			.update({ color: state.color,  template: completionTemplate()})
			.match({ id: query.id })
			if (error) {
				console.log(error)
			} else {
				console.log("Success")
				Router.push('/')
			}
		} else {
			// otherwise show error
			return changeState('error', !state.error)
		}
	}

	return (
		<div className={styles.container}>
      <Head>
        <title>Flexibly - Habit Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>

			<main className={styles.main}>
				<form className={styles.form} onSubmit={handleSubmit}>
					<Link href="/">
						<a className={styles.backDiv}>
							<div className={styles.back}>
								<FontAwesomeIcon  icon={faChevronLeft}></FontAwesomeIcon> {' '}
							</div>
							<div className={styles.backText}>Back</div>
						</a>
					</Link>

					<h1 className={styles.title}>
						Edit <span>Habit</span>
					</h1>

					<div className={styles.firstInput}>
						<div className={`${styles.inputDiv} ${styles.titleDiv}`}>
							<label htmlFor="title">Name this habit</label>
							<input 
								className={styles.textInput} 
								type="text" 
								id="title" 
								name="title" 
								value={query.title}
								readOnly
								// onChange={(event) => changeState("title", event.target.value)}
								required
							/>
						</div>

						<div className={`${styles.inputDiv} ${styles.colorDiv}`}>
							<label htmlFor="color">Color</label>
							<input 
								className={styles.colorInput} 
								type="color" 
								id="color" 
								name="color" 
								value={state.color}
								onChange={(event) => changeState("color", event.target.value)}
							/>
						</div>
					</div>

					<div className={styles.inputDiv}>
						<label htmlFor="description">Describe this habit</label>
						<textarea
							className={styles.textArea}
							id="description" 
							name="description" 
							value={query.description}
							readOnly
							// onChange={(event) => changeState("description", event.target.value)}
						/>
					</div>

					<div className={styles.inputDiv}>
						<label htmlFor="frequency">Habit Frequency</label>

						<div className={styles.frequencyButtons}>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Monday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Monday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Mon </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Tuesday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Tuesday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Tue </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Wednesday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Wednesday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Wed </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Thursday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Thursday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Thu </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Friday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Friday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Fri </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Saturday")?
									styles.selected:
									styles.unselected}`
								} 
								name="frequency" 
								value="Saturday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Sat </button>
							<button 
								className={
									`${styles.frequencyOption}
									${selected("Sunday")?
									styles.selected:
									styles.unselected}`
								}
								name="frequency" 
								value="Sunday"
								onClick={(event) => {
									event.preventDefault()
									changeStatusAndFrequency((event.target as HTMLTextAreaElement).value)
								}}
							> Sun </button>
						</div>
						<div className={
							state.error?
							styles.message:
							styles.hidden
						}>
							Please select when you want to do this habit!
						</div>
					</div>
				  <button className={styles.submit} type="submit">Edit Habit</button>
				</form>
			</main>

			<footer className={styles.footer}>
        <a
          href="https://www.flexibly.ai/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <img className={styles.logo} src="/images/logo.svg" />  {' '}
					Flexibly
        </a>
      </footer>
		</div>
	)
}