import Head from 'next/head'
import Link from 'next/link'
import { useQuery, useMutation, queryCache } from "react-query";
import WeeklyContainer from '../components/WeeklyContainer'

import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus } from "@fortawesome/free-solid-svg-icons";

import moment from 'moment'
import DailyContainer from '../components/dailyContainer'
import useDate from '../hooks/useDate.js';
import axios from 'axios';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import useIsChecked from '../hooks/useIsChecked';
import { prisma } from "../src/db";

// async function fetchHabitsRequest() {
// 	const response = await fetch('/api/habits');
// 	const data = await response.json();
// 	const { habits } = data;
// 	habits = habits.sort((a, b) =>  a.id - b.id)
// 	return habits;
// }

export const getServerSideProps = async () => {
	// const res = await fetch('/api/habits');
	const habits = await prisma.habit.findMany();
	const sortedHabits = habits.sort((a, b) =>  a.id - b.id)
	console.log(habits)
	// const data = await res.json();

	return {
		props: { habits: sortedHabits }
	}
}

export default function Home({ habits }) {
	const { date, time, wish } = useDate();
	const {isChecked, setIsChecked } = useIsChecked();

	const router = useRouter()
	// const [habits, setHabits] = useState([]);

	// useEffect(() => {
	// 	axios.get('/api/habits')
	// 		.then((res) => {
	// 			console.log("Result", res)
	// 			const habitData = [...res.data.habits]
	// 			habitData.sort((a, b) =>  a.id - b.id)
	// 			setHabits(habitData)
	// 		})
	// }, [])
	

	// const {data: habits} = useQuery(['habits'], fetchHabitsRequest, {
	// 	// refetchOnWindowFocus: "always",
	// 	// cacheTime: Infinity
	// })

  return (
    <div className={styles.container}>
      <Head>
        <title>Flexibly - Habit Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>

      <main className={styles.main}>
				<div className={styles.weeklyview}>
					<div className={styles.header}>
						<h1 className={styles.title}>
						{wish} <span>Levon!</span>
						</h1>

						<p className={styles.description}>
							It's {' '}
							<span>
								{time}
								
							</span>
							{' '}
							on <span>{moment().format('dddd')} {moment().format('ll')}</span>
						</p>
					</div>
					<div className={styles.viewheader}>
						<div className={styles.description}>Your habits for the week:</div>
						<Link href="/add-habit">
							<a className={styles.addhabit}>
								<FontAwesomeIcon icon={faPlus}></FontAwesomeIcon> Add Habit
							</a>
						</Link>

					</div>
					<hr/>
					<WeeklyContainer habits={habits} router={router} />
				</div>
				<div className={styles.dailyview}>
					<DailyContainer today={moment().format('dddd')} habits={habits} router={router}/>
				</div>
      </main>
			
      <footer className={styles.footer}>
        <a
          href="https://www.flexibly.ai/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <img className={styles.logo} src="/images/logo.svg" />  {' '}
					Flexibly
        </a>
      </footer>
    </div>
  )
}

