import Head from 'next/head'
import WeeklyContainer from '../components/WeeklyContainer'

import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus } from "@fortawesome/free-solid-svg-icons";

import moment from 'moment'
import Clock from 'react-live-clock'
import DailyContainer from '../components/dailyContainer'

export default function Home() {
	const habits = [
		{
			title: 'Read',
			description: 'Read 30 minutes a day',
			frequency: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
			color: 'red'
		},
		{
			title: 'Workout',
			description: 'Get a sweat in for 1 hour, 3 times a week',
			frequency: ['Monday', 'Wednesday', 'Friday'],
			color: 'blue'
		},
		{
			title: 'Cooking',
			description: 'Make a new recipe',
			frequency: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
			color: 'green'
		},
		{
			title: 'Meditate',
			description: 'Focus',
			frequency: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
			color: 'pink'
		},
		{
			title: 'Journal',
			description: 'Reflect',
			frequency: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
			color: 'orange'
		}
	]

  return (
    <div className={styles.container}>
      <Head>
        <title>Flexibly - Habit Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>

      <main className={styles.main}>
				<div className={styles.weeklyview}>
					<div className={styles.header}>
						<h1 className={styles.title}>
							Welcome <span>Ebuka!</span>
						</h1>

						<p className={styles.description}>
							It's {' '}
							<span>
								<Clock 
									format={'h:mma'}
									ticking={true}	
								/>
							</span>
							{' '}
							on <span>{moment().format('dddd')} {moment().format('ll')}</span>
						</p>
					</div>
					<div className={styles.viewheader}>
						<div className={styles.description}>Your habits for the week:</div>
						<div className={styles.addhabit}><FontAwesomeIcon icon={faPlus}></FontAwesomeIcon> Add Habit</div>

					</div>
					<hr/>
					<WeeklyContainer habits={habits}/>
				</div>
				<div className={styles.dailyview}>
					<DailyContainer habits={habits}/>
				</div>
				

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>
			

      <footer className={styles.footer}>
        <a
          href="https://www.flexibly.ai/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <img className={styles.logo} src="/images/logo.svg" />
        </a>
      </footer>
    </div>
  )
}
